# https://docs.thinkboxsoftware.com/products/deadline/10.1/3_Python%20Reference/index.html

# Create a connection first
import Deadline.DeadlineConnect as Connect
connectionObject = Connect.DeadlineCon('WebServiceName', 8082)

connectionObject.Slaves.GetSlaveNames()
connectionObject.Pools.GetPoolNames()
connectionObject.Groups.GetGroupNames()

# Get a job
job_dict = connectionObject.Jobs.GetJob("qwe")
job_id = job_dict["_id"]
job_name = job_dict["Props"]["Name"]
print(job_dict)
{'Aux': [],
 'Bad': [],
 'ComFra': 0,
 'CompletedChunks': 0,
 'ConcurrencyToken': None,
 'DataSize': -1,
 'Date': '2024-09-04T15:37:39.615-04:00',
 'DateComp': '0001-01-01T00:00:00Z',
 'DateStart': '0001-01-01T00:00:00Z',
 'Errs': 6,
 'ExtraElements': None,
 'FailedChunks': 0,
 'IsSub': True,
 'Mach': 'xxx.com',
 'Main': False,
 'MainEnd': 0,
 'MainStart': 0,
 'OutDir': [],
 'OutFile': [],
 'PendingChunks': 0,
 'Plug': 'CommandLine',
 'Props': {'AWSPortalAssetFileWhitelist': [],
           'AWSPortalAssets': [],
           'AutoTime': False,
           'AuxSync': False,
           'Batch': '',
           'Chunk': 1,
           'Cmmt': 'deadline submit api',
           'Conc': 1,
           'ConcLimt': True,
           'Dep': [],
           'DepComp': True,
           'DepDel': False,
           'DepFail': False,
           'DepFrame': False,
           'DepFrameEnd': 0,
           'DepFrameStart': 0,
           'DepPer': -1.0,
           'Dept': '',
           'Env': {'YOUR_ENV_VARS': 'whatever'},
           'EnvOnly': False,
           'EventDir': '',
           'EventOI': [],
           'Ex0': '',
           'Ex1': '',
           'Ex2': '',
           'Ex3': '',
           'Ex4': '',
           'Ex5': '',
           'Ex6': '',
           'Ex7': '',
           'Ex8': '',
           'Ex9': '',
           'ExDic': {},
           'FrameTimeout': False,
           'Frames': '1',
           'FriStart': '-10675199.02:48:05.4775808',
           'FriStop': '-10675199.02:48:05.4775808',
           'Grp': 'all',
           'InitializePluginTime': 0,
           'Int': False,
           'IntPer': 100,
           'JobFailErr': 0,
           'JobFailOvr': False,
           'Limits': [],
           'ListedSlaves': [],
           'MachLmt': 0,
           'MachLmtProg': -1.0,
           'MaxTime': 0,
           'MinTime': 0,
           'MonStart': '-10675199.02:48:05.4775808',
           'MonStop': '-10675199.02:48:05.4775808',
           'Name': 'xxx',
           'NoBad': False,
           'NoEvnt': False,
           'NotEmail': [],
           'NotNote': '',
           'NotOvr': False,
           'NotUser': ['francois'],
           'OnComp': 2,
           'OptIns': {},
           'OverAutoClean': False,
           'OverClean': False,
           'OverCleanDays': 0,
           'OverCleanType': 1,
           'OvrTaskEINames': False,
           'PathMap': [],
           'PlugDir': '',
           'PlugInfo': {'Shell': 'default',
                        'ShellExecute': 'false',
                        'SingleFramesOnly': 'false'},
           'PoJobScrp': '',
           'PoTskScrp': '',
           'Pool': 'all',
           'PrJobScrp': '',
           'PrTskScrp': '',
           'Pri': 10,
           'Protect': False,
           'Region': '',
           'Reload': False,
           'RemTmT': 0,
           'ReqAss': [],
           'SatStart': '-10675199.02:48:05.4775808',
           'SatStop': '-10675199.02:48:05.4775808',
           'Schd': 0,
           'SchdDate': '2024-09-04T15:37:35.164-04:00',
           'SchdDays': 1,
           'SchdStop': '0001-01-01T00:00:00Z',
           'ScrDep': [],
           'SecPool': 'all',
           'Seq': False,
           'SndEmail': False,
           'SndPopup': False,
           'SndWarn': True,
           'StartTime': 0,
           'SunStart': '-10675199.02:48:05.4775808',
           'SunStop': '-10675199.02:48:05.4775808',
           'TaskEx0': '',
           'TaskEx1': '',
           'TaskEx2': '',
           'TaskEx3': '',
           'TaskEx4': '',
           'TaskEx5': '',
           'TaskEx6': '',
           'TaskEx7': '',
           'TaskEx8': '',
           'TaskEx9': '',
           'Tasks': 1,
           'ThuStart': '-10675199.02:48:05.4775808',
           'ThuStop': '-10675199.02:48:05.4775808',
           'TimeScrpt': False,
           'Timeout': 1,
           'TskFailErr': 0,
           'TskFailOvr': False,
           'TueStart': '-10675199.02:48:05.4775808',
           'TueStop': '-10675199.02:48:05.4775808',
           'User': 'francois',
           'WedStart': '-10675199.02:48:05.4775808',
           'WedStop': '-10675199.02:48:05.4775808',
           'White': False},
 'Purged': False,
 'QueuedChunks': 0,
 'RenderingChunks': 0,
 'SnglTskPrg': '0 %',
 'Stat': 2,
 'SuspendedChunks': 1,
 'Tile': False,
 'TileCount': 0,
 'TileFile': [],
 'TileFrame': 0,
 'TileX': 0,
 'TileY': 0,
 '_id': '111111111111'}

# Get job details
job_details = connectionObject.Jobs.GetJob("qwe")
print(job_details)
{'66d8b8b8a706320eec5b48ff': {'Auxiliary Files': {'No auxiliary files.': ''},
                              'CommandLine Properties': {'Shell': 'default',
                                                         'ShellExecute': 'false',
                                                         'SingleFramesOnly': 'false'},
                              'Dependency Properties': {'Dependency Release Percentage': '',
                                                        'Resume on Completed Dependencies': 'Yes',
                                                        'Resume on Deleted Dependencies': 'No',
                                                        'Resume on Failed Dependencies': 'No',
                                                        'Use Frame Dependencies': 'No'},
                              'Environment Variables': {'PXO_ACES_LUTS_UNC': '/yto-px/o/app/ext/aces'},
                              'Extra Info': {'AppInfo': '',
                                             'DstLocation': '',
                                             'Extra Info 1': '',
                                             'Extra Info 2': '',
                                             'Extra Info 3': '',
                                             'Extra Info 4': '',
                                             'Extra Info 7': '',
                                             'JobMetaData': '',
                                             'SrcLocation': '',
                                             'WranglerNotes': ''},
                              'Extra Info Key/Value Pairs': {'No extra info key/value pairs': ''},
                              'Failure Detection': {'Ignore Bad Worker Detection': 'No',
                                                    'Override Failed Job Detection': 'No',
                                                    'Override Failed Task Detection': 'No',
                                                    'Send Warning For Job Errors': 'Yes'},
                              'General Properties': {'Batch Name': '',
                                                     'Comment': 'deadline '
                                                                'submit api',
                                                     'Concurrent Tasks': '1',
                                                     'Department': '',
                                                     'Enforce Sequential Rendering': 'No',
                                                     'Group': 'all',
                                                     'Job Is Interruptible': 'No',
                                                     'Job Is Protected': 'No',
                                                     "Limit Tasks to Worker's Task Limit": 'Yes',
                                                     'On Job Complete': 'Do '
                                                                        'nothing',
                                                     'Pool': 'all',
                                                     'Priority': '10',
                                                     'Progress cut-off for Job Interruption': '100',
                                                     'Re-synchronize Auxiliary Files Between Tasks': 'No',
                                                     'Reload Plugin Between Tasks': 'No',
                                                     'Remaining Time Threshold for Job Interruption': '0',
                                                     'Secondary Pool': 'all',
                                                     'Suppress Event Plugins': 'No'},
                              'Job': {'Errors': '6',
                                      'Finish Date': '',
                                      'Frames': '1',
                                      'Frames Per Task': '1',
                                      'ID': '11111',
                                      'Mode': 'Normal',
                                      'Name': 'xxx',
                                      'Plugin': 'CommandLine',
                                      'Progress': '0 %   (0/1)',
                                      'Start Date': '',
                                      'Status': 'Suspended',
                                      'Submit Date': '2024/09/04 15:45:00',
                                      'Submit Machine': 'xxx.com',
                                      'User': 'francois'},
                              'Job Dependencies': {'No job dependencies': ''},
                              'Limits': {'No limits': ''},
                              'Machine Limit': {'Limit Stub Release Progress': '(disabled)',
                                                'Machine Limit': '(disabled)'},
                              'Notification Email Addresses': {'No notification emails': ''},
                              'Notification Users': {'User 1': 'me'},
                              'Notifications': {'Notification Method': 'No '
                                                                       'Notification',
                                                'Override Notification Method': 'No'},
                              'Output Directories': {'No output paths.': ''},
                              'Output Filenames': {'No output filenames.': ''},
                              'Required Assets': {'No assets': ''},
                              'Scheduling': {'Mode': 'Disabled'},
                              'Script Dependencies': {'No script dependencies': ''},
                              'Scripts': {'Post Job Script': '',
                                          'Post Task Script': '',
                                          'Pre Job Script': '',
                                          'Pre Task Script': ''},
                              'Statistics': {'Average CPU Usage': '0 %',
                                             'Average Frame Time': '00:00:00:00',
                                             'Average Normalized Frame Time': '00:00:00:00',
                                             'Average Normalized Task Render Time': '00:00:00:00',
                                             'Average Output File Size': '0 '
                                                                         'Bytes',
                                             'Average RAM Usage': '0 Bytes',
                                             'Average Task Render Time': '00:00:00:00',
                                             'Average Task Startup Time': '00:00:00:00',
                                             'Average Task Time': '00:00:00:00',
                                             'Estimated Time Remaining': 'unknown',
                                             'Peak CPU Usage': '0 %',
                                             'Peak RAM Usage': '0 Bytes',
                                             'Running Time': '00:00:00:00',
                                             'Total Normalized Task Render Time': '00:00:00:00',
                                             'Total Output File Size': '0 '
                                                                       'Bytes',
                                             'Total Task Render Time': '00:00:00:00',
                                             'Total Task Startup Time': '00:00:00:00',
                                             'Total Task Time': '00:00:00:00'},
                              'Task States': {'Completed': '0',
                                              'Failed': '0',
                                              'Pending': '0',
                                              'Queued': '0',
                                              'Rendering': '0',
                                              'Suspended': '1'},
                              'Timeouts': {'Auto Task Timeout': 'No',
                                           'Enable Timeouts for Pre/Post Job Scripts': 'No',
                                           'Maximum Render Time': '(no '
                                                                  'maximum)',
                                           'Minimum Render Time': '(no '
                                                                  'minimum)',
                                           'On Task Timeout': 'Error',
                                           'Use the Timeouts for Frames instead of Tasks.': 'No'},
                              'Workers On Deny List': {'No listed Workers': ''}}}
